language: java

jdk:
  - oraclejdk13

script:
  - mkdir out
  - javac -d out -cp out:junit-platform-console-standalone-1.4.2.jar PriorityQueueTest.java
  - java -jar junit-platform-console-standalone-1.4.2.jar -cp out --scan-class-path
