language: java

jdk:
  - oraclejdk13

script:
  - javac -cp junit-platform-console-standalone-1.4.2.jar PriorityQueueTest.java
  - java -jar junit-platform-console-standalone-1.4.2.jar -cp . --scan-class-path
